const Todo = require('../models/Todo');

// @desc    Get all active todos (not deleted)
// @route   GET /api/todos
// @access  Public
const getTodos = async (req, res) => {
    try {
        const todos = await Todo.find({ isDeleted: false }).sort({ createdAt: -1 });
        res.status(200).json(todos);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

// @desc    Get changes for synchronization
// @route   GET /api/todos/sync
// @access  Public
const syncTodos = async (req, res) => {
    try {
        const { since } = req.query; // Timestamp string or epoch
        let query = {};

        if (since) {
            const sinceDate = new Date(since);
            if (!isNaN(sinceDate)) {
                // Fetch items updated/created/deleted AFTER 'since'
                query = { updatedAt: { $gt: sinceDate } };
            }
        }

        // Return all matching items, INCLUDING deleted ones so client knows to remove them
        const todos = await Todo.find(query).sort({ updatedAt: 1 });

        res.status(200).json({
            timestamp: new Date().toISOString(), // Current server time for next sync
            changes: todos,
        });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

// @desc    Create a new todo
// @route   POST /api/todos
// @access  Public
const createTodo = async (req, res) => {
    try {
        // Validate that syncId is provided by the client
        if (!req.body.syncId) {
            return res.status(400).json({
                message: 'syncId is required and must be generated by the client (UUID v4 recommended)'
            });
        }

        const todo = await Todo.create(req.body);
        res.status(201).json(todo);
    } catch (error) {
        // Handle duplicate syncId error
        if (error.code === 11000) {
            return res.status(409).json({
                message: 'A todo with this syncId already exists'
            });
        }
        res.status(400).json({ message: error.message });
    }
};

// @desc    Update a todo
// @route   PATCH /api/todos/:syncId
// @access  Public
const updateTodo = async (req, res) => {
    try {
        const todo = await Todo.findOne({ syncId: req.params.syncId });

        if (!todo) {
            return res.status(404).json({ message: 'Todo not found' });
        }

        // Prevent updating syncId via PATCH
        if (req.body.syncId && req.body.syncId !== req.params.syncId) {
            return res.status(400).json({ message: 'Cannot modify syncId' });
        }

        // Allow updates to revive soft-deleted items or modify any field
        const updatedTodo = await Todo.findOneAndUpdate(
            { syncId: req.params.syncId },
            req.body,
            { new: true, runValidators: true } // Returns the updated document
        );

        res.status(200).json(updatedTodo);
    } catch (error) {
        res.status(400).json({ message: error.message });
    }
};

// @desc    Soft delete a todo
// @route   DELETE /api/todos/:syncId
// @access  Public
const deleteTodo = async (req, res) => {
    try {
        const todo = await Todo.findOne({ syncId: req.params.syncId });

        if (!todo) {
            return res.status(404).json({ message: 'Todo not found' });
        }

        // Soft delete: set isDeleted to true
        todo.isDeleted = true;
        await todo.save();

        res.status(200).json({ syncId: todo.syncId, message: 'Todo soft deleted', isDeleted: true });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
};

module.exports = {
    getTodos,
    syncTodos,
    createTodo,
    updateTodo,
    deleteTodo,
};
