const mongoose = require('mongoose');

const TodoSchema = new mongoose.Schema(
    {
        // MongoDB's internal _id (ObjectId) - never exposed to clients
        syncId: {
            type: String,
            required: [true, 'syncId is required and must be generated by the client'],
            unique: true,
            index: true,
            trim: true,
        },
        title: {
            type: String,
            required: [true, 'Please add a title'],
            trim: true,
        },
        description: {
            type: String,
            default: '',
            trim: true,
        },
        isCompleted: {
            type: Boolean,
            default: false,
        },
        isDeleted: {
            type: Boolean,
            default: false, // For soft deletes (tombstoning)
        },
        version: {
            type: Number,
            default: 1, // Simple versioning for conflict resolution
        },
    },
    {
        timestamps: true, // Adds createdAt and updatedAt automatically
        toJSON: {
            transform: function (doc, ret) {
                // Remove MongoDB internal fields from JSON responses
                delete ret._id;
                delete ret.__v;
                return ret;
            },
        },
    }
);

// Middleware to increment version on updates (not on initial creation)
TodoSchema.pre('save', function () {
    // Only increment version if this is an update, not a new document
    if (!this.isNew && this.isModified()) {
        this.version += 1;
    }
});

module.exports = mongoose.model('Todo', TodoSchema);
